name: ChestLock
author: Skyladd
version: 1.0.0
main: Skyladd\ChestLock
load: POSTWORLD
api: 2.0.0
website: "https://github.com/Skyladd/ChestLock/"
commands:
  chest:
    description: "Lock your chests"
    usage: "/chest"
    permission: chestlock
    default: true
  chestop:
    description: "Unlock Chests"
    usage: "/chestop"
    permission: chestlock.op
    default: op
permissions:
  chestlock:
    default: true
    description: "Lock Your Chests"
  chestlock.op:
    default: op
    description: "Unlock Chests"
  
